apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: backend
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-06-03T02:31:13Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: backend
  namespace: default
  resourceVersion: "9196"
  uid: 8b021627-189e-4f43-93df-8408b72e0de8
spec:
  clusterIP: 172.20.194.234
  clusterIPs:
  - 172.20.194.234
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}